#########################################################################
# Title:         Pre-Tasks Role - User Task                             #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "User | Check if user '{{ user }}' exists"
  shell: "id -un {{ user }} >/dev/null 2>&1;"
  register: user_check
  failed_when: user_check.rc > 1

- name: "User | Set user variables when '{{ user }}' exists"
  block:

  - name: "User | Get '{{ user }}' info"
    user:
      name: "{{ user }}"
    register: user_info

  - name: "User | Get 'video' gid"
    shell: "getent group video | cut -d: -f3"
    register: vgid_lookup

  - name: "User | Set 'uid', 'gid', and 'vgid'"
    set_fact:
      uid: "{{ user_info.uid }}"
      gid: "{{ user_info.group }}"
      vgid: "{{ vgid_lookup.stdout }}"

  when: user_check.rc == 0
