#########################################################################
# Title:         Cloudbox: Shell Role - Bash Task                       #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check if '.bashrc' exists
  stat:
    path: "/home/{{ user.name }}/.bashrc"
  register: bashrc

- name: "Copy '/etc/skel/.bashrc' to '/home/{{ user.name }}/.bashrc'"
  copy:
    src: "/etc/skel/.bashrc"
    dest: "/home/{{ user.name }}/.bashrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: no
  when: not bashrc.stat.exists

- name: Set default editor to nano in '.bashrc'
  lineinfile:
    dest: "/home/{{ user.name }}/.bashrc"
    regexp: "^export EDITOR="
    line: "export EDITOR=nano"
    state: present

- name: Set bash as default shell
  user:
    name: "{{ user.name }}"
    shell: /bin/bash
  register: default_shell

- name: "Default shell set to: Bash"
  debug:
    msg:
      - "Default shell set to: Bash"
  when: (default_shell is changed)

- name: "Default shell set to: Bash"
  debug:
    msg:
      - "Changes will apply on session restart."
  when: (default_shell is changed) and ('shell' in ansible_run_tags)
