#########################################################################
# Title:         Backup: Snapshot                                       #
# Author(s):     desimaniac, RXWatcher1                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Snapshot | Set default variables
  set_fact:
    snapshot_type: ""
    backup_root_path: ""
    use_snapshot: false

- name: "Snapshot | Determine '/' filesystem type"
  set_fact:
    root_fstype: "{{ item.fstype }}"
  when: "(item.mount == '/')"
  with_items:
    - "{{ ansible_mounts }}"

- name: Snapshot | Btrfs specific tasks
  block:

  - name: "Snapshot | Set btrfs variables"
    set_fact:
      snapshot_type: "btrfs"
      backup_root_path: "/btrfs/snapshots/root"
      # variable(s) below will be used for other types of snap-shotting as well.
      use_snapshot: true

  - name: Snapshot | Check if btrfs snapshot is mounted
    stat:
      path: "/btrfs/snapshots/root"
    register: btrfs_snapshot_mounted

  - name: Snapshot | Delete old btrfs snapshot
    command: "btrfs subvolume delete /btrfs/snapshots/root"
    when: (btrfs_snapshot_mounted.stat.isdir is defined) and (btrfs_snapshot_mounted.stat.isdir)

  - name: Snapshot | Create brfs snapshot directory
    file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
    with_items:
      - /btrfs/snapshots

  when: (misc.snapshot) and ((root_fstype is defined) and (root_fstype == 'btrfs'))
