#########################################################################
# Title:         System: Mounts Tasks                                   #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- debug:
    msg: "System mounts: are {{ ansible_mounts }}"

- name: Set noatime,nobarrier opts for / mount
  mount:
    path: /
    opts: defaults,noatime,nobarrier
    state: present
    fstype: ext4
    src: "{{ item.device }}"
  with_items:
    - "{{ ansible_mounts }}"
  when: (item.mount == '/') and (item.fstype == 'ext4')
