#########################################################################
# Title:         Cloudbox: Radarr4K - Suitarr Migration Tasks           #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Suitarr Migration | Check folder exists
  stat:
    path: /opt/radarr4k
  register: folder

- name: Suitarr Migration | Check subfolder1 exists
  stat:
    path: /opt/radarr4k/Radarr
  register: subfolder1

- name: Suitarr Migration | Check subfolder2 exists
  stat:
    path: /opt/radarr4k/app
  register: subfolder2

- name: Suitarr Migration | Move 'radarr4k' folder contents to 'app' subfolder
  shell: |
    mv /opt/radarr4k /tmp/app
    mkdir /opt/radarr4k
    mv /tmp/app /opt/radarr4k/
    find /opt/radarr4k/* -type d -empty -delete
    chown -R {{ user.name }}:{{ user.name }} /opt/radarr4k
  when: (folder.stat.exists) and not (subfolder1.stat.exists or subfolder2.stat.exists)

- name: Suitarr Migration | Move 'Radarr' subfolder to 'app' subfolder
  shell: |
    mv /opt/radarr4k/Radarr /opt/radarr4k/app
    chown -R {{ user.name }}:{{ user.name }} /opt/radarr4k
  when: (folder.stat.exists) and (subfolder1.stat.exists) and (not subfolder2.stat.exists)
