#########################################################################
# Title:         Cloudbox: Qbittorrent Role                             #
# Author(s):     l3uddz, desimaniac, horjulf                            #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  horjulf/rutorrent-autodl                               #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: qbittorrent
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: qbittorrent
    state: absent

- name: Create rutorrent directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }} recurse=yes"
  with_items:
    - "/opt/qbittorrent"
    - "{{ downloads.torrents }}"
    - "{{ downloads.torrents }}/rutorrent"
    - "{{ downloads.torrents }}/rutorrent/completed"
    - "{{ downloads.torrents }}/rutorrent/watched"

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/qbittorrent:/config"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"

- name: Create and start container
  docker_container:
    name: qbittorrent
    image: linuxserver/qbittorrent
    pull: yes
    published_ports:
      - "127.0.0.1:8080:80"
      - "51413:51413"
      - "51413:51413/udp"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "qbittorrent.{{ user.domain }}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "qbittorrent.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes: "{{ default_volumes + torrents_downloads_path|default([]) }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - qbittorrent
    purge_networks: yes
    restart_policy: unless-stopped
    stop_timeout: 900
    state: started

- name: Qbittorrent Settings Tasks
  include_tasks: "settings/main.yml"
  when: (not continuous_integration)
