#########################################################################
# Title:         Remote: Rclone VFS Tasks                               #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/Cloudbox/Cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Rclone VFS | Reset permissions for 'rclone.conf'
  file: "path={{ item }} state=file mode=0775 owner={{ user }} group={{ user }}"
  with_items:
    - "/home/{{ user }}/.config/rclone/rclone.conf"

- name: Rclone VFS | Import 'rclone_vfs.service'
  template:
    src: rclone_vfs.service.j2
    dest: /etc/systemd/system/rclone_vfs.service
    force: "{{ 'yes' if ('mounts_override' in ansible_run_tags) else 'no' }}"

- name: Rclone VFS | Systemd daemon-reload 'rclone_vfs.service'
  systemd: name=rclone_vfs.service state=stopped enabled=no daemon_reload=yes

- name: Rclone VFS | Import 'rclone_vfs_primer.timer'
  template:
    src: rclone_vfs_primer.timer.j2
    dest: /etc/systemd/system/rclone_vfs_primer.timer
    force: "{{ 'yes' if ('mounts_override' in ansible_run_tags) else 'no' }}"

- name: Rclone VFS | Systemd daemon-reload 'rclone_vfs_primer.timer'
  systemd: name=rclone_vfs_primer.timer state=stopped enabled=no daemon_reload=yes

- name: Rclone VFS | Import 'rclone_vfs_primer.service'
  template:
    src: rclone_vfs_primer.service.j2
    dest: /etc/systemd/system/rclone_vfs_primer.service
    force: "{{ 'yes' if ('mounts_override' in ansible_run_tags) else 'no' }}"

- name: Rclone VFS | Systemd daemon-reload 'rclone_vfs_primer.service'
  systemd: name=rclone_vfs_primer.service state=stopped enabled=no daemon_reload=yes

- name: Rclone VFS | Test rclone remote
  shell: "rclone lsd {{ rclone.remote }}:"
  become: yes
  become_user: "{{ user }}"
  register: rclone_test
  failed_when: (rclone_test.rc|int > 5)

- name: Rclone VFS | Start up services when rclone remote is configured
  block:

  - name: Rclone VFS | Start 'rclone_vfs.service'
    systemd: name=rclone_vfs.service state=started enabled=yes

  - name: Rclone VFS | "Wait for 5 seconds"
    wait_for:
      timeout: 5

  - name: Rclone VFS | Start 'rclone_vfs_primer.timer'
    systemd: name=rclone_vfs_primer.timer state=started enabled=yes

  - name: Rclone VFS | Start 'rclone_vfs_primer.service'
    systemd: name=rclone_vfs_primer.service state=started enabled=yes

  when: (rclone_test.rc|int == 0)
