#########################################################################
# Title:         Cloudbox: Remote Role                                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Sanity Check
- name: Sanity Check Tasks
  import_tasks: "subtasks/sanity_checks.yml"

# Stop Containers

- name: Container Tasks
  import_tasks: "subtasks/containers.yml"
  when: ('mounts' in ansible_run_tags) or ('mounts_override' in ansible_run_tags)

# Existing Setup

- name: Legacy Tasks
  import_tasks: "subtasks/legacy.yml"

- name: Service Tasks
  include_tasks: "subtasks/services.yml"
  loop_control:
    loop_var: outer_item
  loop:
    - "plexdrive4.service"
    - "plexdrive5.service"
    - "rclone_vfs.service"
    - "rclone_cache.service"
    - "rclone_vfs_primer.service"
    - "rclone_vfs_primer.timer"

- name: Mount Tasks
  import_tasks: "subtasks/mounts.yml"

# New Setup

- name: Fuse Tasks
  import_tasks: "subtasks/fuse.yml"

- name: Basic Tasks
  import_tasks: "subtasks/basics.yml"

- name: Plexdrive Tasks
  block:

  - name: Plexdrive 4 Tasks
    import_tasks: "subtasks/plexdrive4.yml"
    when: ((ansible_memory_mb.real.total/1024)|round(0,'ceil')|int < 8)

  - name: Plexdrive 5 Tasks
    import_tasks: "subtasks/plexdrive5.yml"
    when: ((ansible_memory_mb.real.total/1024)|round(0,'ceil')|int >= 8)

  when: (mounts.remote | lower == 'plexdrive')

- name: Plexdrive 4 Tasks
  import_tasks: "subtasks/plexdrive4.yml"
  when: (mounts.remote | lower == 'plexdrive4') or (mounts.remote | lower == 'plexdrive_4')

- name: Plexdrive 5 Tasks
  import_tasks: "subtasks/plexdrive5.yml"
  when: (mounts.remote | lower == 'plexdrive5') or (mounts.remote | lower == 'plexdrive_5')

- name: Rclone Cache Tasks
  import_tasks: "subtasks/rclone_cache.yml"
  when: (mounts.remote | lower == 'rclone_cache')

- name: Rclone VFS Tasks
  import_tasks: "subtasks/rclone_vfs.yml"
  when: (mounts.remote | lower == 'rclone_vfs')
