#########################################################################
# Title:         Cloudbox: Settings Role                                #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Install ruamel.yaml"
  pip:
    name: ruamel.yaml
    version: 0.15.35
    executable: pip3

- name: "Get 'cloudbox.yml' info."
  stat:
    path: "{{ playbook_dir }}/cloudbox.yml"
  register: cloudbox_yml

- name: "Settings: Ansible Config"
  include_tasks: "ansible_config.yml"
  with_items:
    - "ansible.cfg"

- name: "Setting: Settings Migrator"
  include_tasks: "settings_migrator.yml"
  with_items:
    - "backup_config.yml"

- name: Initialize empty lists and vars
  set_fact:
    files_updated_successfully: []
    files_updated_unsuccessfully: []
    exit_is_necessary: false

- name: "Setting: Settings Updater"
  include_tasks: "settings_updater.yml"
  with_items:
    - "accounts.yml"
    - "settings.yml"
    - "adv_settings.yml"
    - "backup_config.yml"

- name: "Settings: Exit After Changes"
  include_tasks: "exit.yml"
